### ISSUE TITLE
When I setting package Igot error . Error encountered; filesystem operation aborted.

### ISSUE THREAD

**Issue by asps946701** [clearpathrobotics/robot_upstart#116]
Hi I first time try to use robot_upstart  but get error 
Could anyone help me ?  Thank!

**system information**
-melodic
-jetson nano ubuntu 18.04

**my command :**
1.sudo apt-get install ros-melodic-robot-upstart
2.source .bashrc
3.rosrun robot_upstart install usb_cam/launch/usb_cam-test.launch

**Error massage is below** 
b'/lib/systemd/systemd'
Preparing to install files to the following paths:
  /etc/ros/melodic/usb.d/.installed_files
  /etc/ros/melodic/usb.d/usb_cam-test.launch
  /etc/systemd/system/multi-user.target.wants/usb.service
  /lib/systemd/system/usb.service
  /usr/sbin/usb-start
  /usr/sbin/usb-stop
Now calling: /usr/bin/sudo /opt/ros/melodic/lib/robot_upstart/mutate_files
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/robot_upstart/mutate_files", line 37, in <module>
    installation_files = pickle.loads(sys.argv[1])
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '{'
Error encountered; filesystem operation aborted.
** To complete installation please run the following command:
 sudo systemctl daemon-reload && sudo systemctl start usb

**than using : sudo systemctl daemon-reload && sudo systemctl start usb**
Failed to start usb.service: Unit usb.service not found.

**Comment by Pran-Seven** [comment]
You could modify your service file to look for when USB service starts and then launch, or retry on failure to make sure it keeps trying until usb service is available.
https://superuser.com/questions/1322777/in-systemd-service-file-how-do-i-say-after-usb-is-ready this link might help you setup the service so that you can launch after usb service is ready
